--New SECOND_PAIR_CODE Attribute
Create Table PREP_SECOND_PAIR_CODE_TABLE AS
SELECT max(sup.SUP_HEADER_SK) as SUP_HEADER_SK, sup.SOURCE_CUSTOMER_ID, Count(sup.TRANSNUMBER) AS TRANS_COUNT
FROM $base..SALES_SALES_HEADER_SUP sup
left join $base..SALES_SALES_HEADER sh on sup.TRANS_HEADER_SK = sh.TRANS_HEADER_SK
left join $base..SALES_SALES_DETAIL sd on sh.TRANS_HEADER_SK = sd.TRANS_HEADER_SK
left join  $precalc..PRECALC__OFFERING_ATTR_VALUES oav on oav.ARTICLE_KEY = sd.OFFERING_KEY 
WHERE sup.SOURCE_RICEF = 'I_CRM_0163' and sh.TOTAL_NET_VALUE > 0
and (oav.MERCH_CATEGORY3 in ('01','02','09','04','10') or oav.MERCH_CATEGORY2 = '5005')
GROUP BY sup.SOURCE_CUSTOMER_ID, sup.SOURCE_SITE, sup.TRANSACTION_DATE
ORDER BY TRANS_COUNT
;

Create Table NEW_SECOND_PAIR_CODE_TABLE AS
Select sup.SUP_HEADER_SK, SECOND_PAIR_CODE,
CASE 
WHEN SOURCE_RICEF = 'I_CRM_0163' AND TRANS_COUNT > 1 THEN (TRANS_COUNT - 1)::varchar(2)
WHEN SOURCE_RICEF = 'I_CRM_0163' AND (TRANS_COUNT = 1 OR TRANS_COUNT IS NULL) THEN '0'
ELSE SECOND_PAIR_CODE
END AS SECOND_PAIR_CODE_CALC
FROM $base..SALES_SALES_HEADER_SUP sup
left join PREP_SECOND_PAIR_CODE_TABLE prep on sup.SUP_HEADER_SK = prep.SUP_HEADER_SK
;





