-- region data preparation
call $base_db..ut_drop_table_if_exists('PREP_SECOND_PAIR_CODE_TABLE_NEW');
create  table PREP_SECOND_PAIR_CODE_TABLE_NEW as 
select 
te.SUP_HEADER_SK
,case 
	when TOTAL_NET_VALUE > 0 then (row_number() over (partition by SOURCE_CUSTOMER_ID, SOURCE_SITE, TRANSACTION_DATE order by TRANSNUMBER)-1)::varchar(10)
	else '0'
	end as SECOND_PAIR_CODE
from 	
(
select 
sup.SUP_HEADER_SK
,sh.TOTAL_NET_VALUE
,sup.SOURCE_CUSTOMER_ID
,sup.SOURCE_SITE
,sup.TRANSACTION_DATE
,sup.TRANSNUMBER
FROM $base_db..SALES_SALES_HEADER_SUP sup
join $base_db..SALES_SALES_HEADER sh on sup.TRANS_HEADER_SK = sh.TRANS_HEADER_SK
join $base_db..SALES_SALES_DETAIL sd on sh.TRANS_HEADER_SK = sd.TRANS_HEADER_SK
join  $precalc_db..PRECALC__OFFERING_ATTR_VALUES oav on oav.ARTICLE_KEY = sd.OFFERING_KEY 
WHERE (oav.MERCH_CATEGORY3 in ('01','02','09','04','10') or oav.MERCH_CATEGORY2 = '5005')
and sup.SOURCE_RICEF = 'I_CRM_0163'
group by 1,2,3,4,5,6
) te
distribute on (SUP_HEADER_SK)
;
-- end region

-- region main template
alter table SALES_HEADER_SUP rename to SALES_HEADER_SUP_OLD
;

create table SALES_HEADER_SUP as 
Select 
 TRANSACTION_DATE
, SOURCE_RICEF
, SOURCE_SITE
, SALES_ORGANIZATION
, DISTRIBUTION_CHANNEL
, SOURCE_CUSTOMER_ID
, EYENET_POS_TRANSACTIONNUMBER
, TRANSNUMBER
, EYENET_POS_RCPID
, WORKORDER_NUMBER
, WORKORDER_DATE
, EYENET_TRANSACTIONTYPECODE
,case 
	when sup.SOURCE_RICEF = 'I_CRM_0163' then nvl(prep.SECOND_PAIR_CODE,'0')
	else sup.SECOND_PAIR_CODE
	end as SECOND_PAIR_CODE
, COPAY_AMT
, PLAN_CODE
, BENEFIT_LEVEL_CODE
, MEMBER_ID
, DOCTOR_ID
, DOCTOR_TYPE_CODE
, EXAM_DATE
, EXPIRES_DATE
, SPECIAL_ORDER
, SPECIAL_ORDER_CODE
, SPECIAL_ORDER_DATE
, CREATED_BY_RICEF
, CREATED_BY_USER
, CREATED_BY_DATETIME
, sup.SUP_HEADER_SK
, TRANS_HEADER_SK
, FISCAL_DATE_KEY
, RECORD_DATE
, PERSONA_KEY
, EYENET_TYPE_CODE_KEY
, WORK_ORDER_KEY
FROM $report_db..SALES_HEADER_SUP_OLD sup 
left join PREP_SECOND_PAIR_CODE_TABLE prep on sup.SUP_HEADER_SK = prep.SUP_HEADER_SK
DISTRIBUTE ON (TRANS_HEADER_SK);

drop table SALES_HEADER_SUP_OLD
;
-- end region
